#!/bin/bash

#| |/ (_) | |(_) ___  _   _      |  _ \ / _ \_   _|  |___ \   |_   _|_  _| |_ 
#| ' /| | | || |/ _ \| | | |_____| |_) | | | || |_____ __) |____| | \ \/ / __|
#| . \| | | || | (_) | |_| |_____|  _ <| |_| || |_____/ __/_____| |  >  <| |_ 
#|_|\_\_|_|_|/ |\___/ \__, |     |_| \_\\___/ |_|    |_____|    |_| /_/\_\\__|
#          |__/       |___/              



echo -e "| |/ (_) | |(_) ___  _   _      |  _ \ / _ \_   _|  |___ \   |_   _|_  _| |_\n| ' /| | | || |/ _ \| | | |_____| |_) | | | || |_____ __) |____| | \ \/ / __|\n| . \| | | || | (_) | |_| |_____|  _ <| |_| || |_____/ __/_____| |  >  <| |_ \n|_|\_\_|_|_|/ |\___/ \__, |     |_| \_\\____/ |_|    |_____|    |_| /_/\_\\__|\n          |__/       |___/"





text=$1
echo "The text you want to uncipher is: $1"

echo "---ROT-2---"
ROT2="$(echo $text | tr 'c-za-cC-ZA-B' 'a-zA-Z')"
echo $ROT2

echo "---ROT-3---"
ROT3="$(echo $text | tr 'd-za-cD-ZA-C' 'a-zA-Z')"
echo $ROT3

echo "---ROT-4---"
ROT4="$(echo $text | tr 'e-za-dE-ZA-D' 'a-zA-Z')"
echo $ROT4

echo "---ROT-5---"
ROT5="$(echo $text | tr 'f-za-eF-ZA-E' 'a-zA-Z')"
echo $ROT5

echo "---ROT-6---"
ROT6="$(echo $text | tr 'g-za-fG-ZA-F' 'a-zA-Z')"
echo $ROT6

echo "---Rot-7---"
ROT7="$(echo $text | tr 'h-za-gH-ZA-G' 'a-zA-Z')"
echo $ROT7

echo "---ROT-8---"
ROT8="$(echo $text | tr 'i-za-hI-ZA-H' 'a-zA-Z')"
echo $ROT8

echo "---ROT-9---"
ROT9="$(echo $text | tr 'j-za-iJ-ZA-I' 'a-zA-Z')"
echo $ROT9

echo "---ROT-10---"
ROT10="$(echo $text | tr 'k-za-jK-ZA-J' 'a-zA-Z')"
echo $ROT10

echo "---ROT-11---"
ROT11="$(echo $text | tr 'l-za-kL-ZA-K' 'a-zA-Z')"
echo $ROT11

echo "---ROT-12---"
ROT12="$(echo $text | tr 'm-za-lM-ZA-L' 'a-zA-Z')"
echo $ROT12

echo "---ROT-13---"
ROT13="$(echo $text | tr 'n-za-mN-ZA-M' 'a-zA-Z')"
echo $ROT13

echo "---ROT-14---"
ROT14="$(echo $text | tr 'o-za-nO-ZA-N' 'a-zA-Z')"
echo $ROT14

echo "---ROT-15---"
ROT15="$(echo $text | tr 'p-za-oP-ZA-O' 'a-zA-Z')"
echo $ROT15

echo "---ROT-16---"
ROT16="$(echo $text | tr 'q-za-pQ-ZA-P' 'a-zA-Z')"
echo $ROT16

echo "---ROT-17---"
ROT17="$(echo $text | tr 'r-za-qR-ZA-Q' 'a-zA-Z')"
echo $ROT17

echo "---ROT-18---"
ROT18="$(echo $text | tr 's-za-rS-ZA-R' 'a-zA-Z')"
echo $ROT18

echo "---ROT-19---"
ROT19="$(echo $text | tr 't-za-sT-ZA-S' 'a-zA-Z')"
echo $ROT19

echo "---ROT-20---"
ROT20="$(echo $text | tr 'u-za-tU-ZA-T' 'a-zA-Z')"
echo $ROT20

echo "---ROT-21---"
ROT21="$(echo $text | tr 'v-za-uV-ZA-U' 'a-zA-Z')"
echo $ROT21

echo "---ROT-22---"
ROT22="$(echo $text | tr 'w-za-vW-ZA-V' 'a-zA-Z')"
echo $ROT22

echo "---ROT-23---"
ROT23="$(echo $text | tr 'x-za-wX-ZA-W' 'a-zA-Z')"
echo $ROT23

echo "---ROT-24---"
ROT24="$(echo $text | tr 'y-za-xY-ZA-X' 'a-zA-Z')"
echo $ROT24

echo "---ROT-25---"
ROT25="$(echo $text | tr 'z-za-yZ-ZA-Y' 'a-zA-Z')"
echo $ROT25
